---
title: "Univariate BV and (RV-BV)"
author: "CID: 01714151"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
base::summary(abs(EU_flat$log_return))
quantile(abs(EU_flat$log_return), probs=c(0.8, 0.9, 0.95, 0.99))

base::summary(abs(AU_flat$log_return))
quantile(abs(AU_flat$log_return), probs=c(0.8, 0.9, 0.95, 0.99))
```
## Explore BPV and J = (RV-BPV)
```{r}
acf(EU_daily2$rbpv, lag.max=30, main="EURUSD Daily Realized Bipower, 2022 May - 2023 Apr")
acf(EU_daily2$jump, lag.max=30, main="EURUSD Daily Realized jumps (RV-BPV), 2022 May - 2023 Apr")
```
## HAR In-sample forecasting for $\sigma^2$
```{r}
# Estimate the model on full data sample
EU_HAR_in_model_bv <- comp_har_pred(23, 256, sqrt(EU_daily2$rbpv))$model
EU_HAR_in_model_bv$coefficients
# Compute adjusted R^2 of the fitted BPV model
base::summary(EU_HAR_in_model_bv)$adj.r.squared

EU_HAR_inpred_bv <- data.frame(date=EU_daily2$date[24:257], pred=predict(EU_HAR_in_model_bv)*mu1^(-1), true=sqrt(EU_daily2$rbpv[24:257]*mu1^(-2)))
# Plot the HAR in-sample forecast
EU_HAR_inpred_plot_bv <- ggplot(data=EU_HAR_inpred_bv, aes(x=date)) +
  geom_line(aes(y=true, color='realized √BPV/µ1')) +
  geom_line(aes(y=pred, color='HAR BPV pred')) +
  scale_color_manual(name=NULL, values=c('realized √BPV/µ1' = 'darkgrey', "HAR BPV pred" = "steelblue")) +
  ggtitle("HAR_BPV in-sample forecast from 2022 May - 2023 Apr") +
  ylab("BPV value") +
  xlab("Date") +
  theme_classic() +
  theme(plot.title = element_text(size = 13.5),
        axis.title = element_text(size= 12.5),
        axis.text = element_text(size= 11.5),
        legend.title = element_text(size= 11),
        legend.text = element_text(size= 11),
        legend.position = c(0.85, 0.85))

EU_HAR_inpred_plot_bv
```

## HAR_bv Out-of-sample forecasting for $\sigma^2$
```{r echo=FALSE}
# Obtain the one-day out-of-sample forecast and 0.95 CI of the rolling window
EU_HAR_outpred_bv <- data.frame(do.call(rbind, lapply(EU_roll_start:EU_roll_end, function(x){comp_har_pred(x-train_length, x, sqrt(EU_daily2$rbpv))$pred*mu1^(-1)})), row.names = NULL)
EU_HAR_outpred_bv$date = EU_daily2$date[(EU_roll_start+2) : (EU_roll_end+2)]
EU_HAR_outpred_bv$true = sqrt(EU_daily2$rbpv[(EU_roll_start+2) : (EU_roll_end+2)]*mu1^(-2))

mean((EU_HAR_inpred_bv$pred - EU_HAR_inpred_bv$true)^2)
mean((EU_HAR_outpred_bv$true - EU_HAR_outpred_bv$fit)^2)

# Plot the HAR out-of-sample forecast
EU_daily2_23 <- EU_daily2[year(EU_daily2$date)==2023,]
EU_HAR_outpred_plot_bv <- ggplot() +
  geom_line(data=data.frame(x=EU_daily2_23$date, y=sqrt(EU_daily2_23$rbpv*mu1^(-2))), 
            aes(x = x, y = y, color = "realized BV")) +
  geom_line(data=data.frame(x=EU_HAR_outpred_bv$date, y=EU_HAR_outpred_bv$fit), 
            aes(x = x, y = y, color = "HAR_BV pred")) +
  geom_ribbon(data=data.frame(x=EU_HAR_outpred_bv$date, lwr=EU_HAR_outpred_bv$lwr, upr = EU_HAR_outpred_bv$upr), aes(x = x, ymin = lwr, ymax=upr), fill = "lightblue", alpha=0.3) +
  scale_color_manual(name=NULL, values=c('realized BP' = 'darkgrey', "HAR_BV pred" = "darkblue")) +
  theme_classic() +
  ggtitle("HAR_BV out-of-sample forecast from 2023 Mar-Apr") +
  xlab("Date") + ylab("BV value") +
  theme(plot.title = element_text(size = 13.5),
        axis.title = element_text(size= 12.5),
        axis.text = element_text(size= 11.5),
        legend.title = element_text(size= 11),
        legend.text = element_text(size= 11),
        legend.position = c(0.85, 0.85))

EU_HAR_outpred_plot_bv

#grid.arrange(EU_HAR_inpred_plot_bpv, EU_HAR_outpred_plot_bpv, ncol=2)
```

## HAR, dHAR and naive in-sample prediction for J(ump)
```{r}
# Estimate the model HAR_J
EU_HAR_in_model_jump <- comp_har_pred(23, 256, sqrt(EU_daily2$jump))$model
EU_HAR_in_model_jump$coefficients
base::summary(EU_HAR_in_model_jump)$adj.r.squared

# Estimate the model HAR_adj.J
#EU_HAR_in_model_adj.jump <- comp_har_pred(23, 256, sqrt(EU_daily2$adj.jump))$model
#EU_HAR_in_model_adj.jump$coefficients
#base::summary(EU_HAR_in_model_adj.jump)$adj.r.squared

# Estimate the model dHAR_J
EU_dHAR_in_model_jump <- comp_dhar_pred(23, 256, sqrt(EU_daily2$jump))$model
EU_dHAR_in_model_jump$coefficients
base::summary(EU_dHAR_in_model_jump)$adj.r.squared

# Estimate the model dHAR_adjJ
#EU_dHAR_in_model_adj.jump <- comp_dhar_pred(23, 256, sqrt(EU_daily2$adj.jump))$model
#EU_dHAR_in_model_adj.jump$coefficients
#base::summary(EU_dHAR_in_model_adj.jump)$adj.r.squared

# Estimate the model Naive_J
EU_naive_in_jump <- sqrt(EU_daily2$jump[23:256])
```

## BPV+J in-sample forecast
```{r}
# HAR_BPV + HAR_J
EU_inpred_bvJ <- data.frame(date=EU_daily2$date[24:257], true=sqrt(EU_daily2$rvar[24:257]),
                             HAR_pred=sqrt((predict(EU_HAR_in_model_bv)*mu1^(-1))^2 + 
                                             predict(EU_HAR_in_model_jump)^2),
                             dHAR_pred=sqrt((predict(EU_HAR_in_model_bv)*mu1^(-1))^2 +
                                              predict(EU_dHAR_in_model_jump)^2),
                             naive_pred=sqrt((predict(EU_HAR_in_model_bv)*mu1^(-1))^2 +
                                               EU_naive_in_jump^2))

# Plot the HAR in-sample forecast
EU_HAR_inpred_plot_bvJ <- ggplot(data=EU_inpred_bvJ, aes(x=date)) +
  geom_line(aes(y=true, color='RVol')) +
  geom_line(aes(y=HAR_pred, color='in-sample pred')) +
  scale_color_manual(name=NULL, values=c('RVol' = 'darkgrey', "in-sample pred" = "steelblue")) +
  ggtitle("HAR in-sample Forecast for diffusive parts on EURUSD from 2022 May - 2023 Apr") +
  ylab("BPV+J") +
  theme_classic()

EU_HAR_inpred_plot_bvJ

EU_dHAR_inpred_plot_bvJ <- ggplot(data=EU_inpred_bvJ, aes(x=date)) +
  geom_line(aes(y=true, color='RVol')) +
  geom_line(aes(y=dHAR_pred, color='in-sample pred')) +
  scale_color_manual(name=NULL, values=c('RVol' = 'darkgrey', "in-sample pred" = "steelblue")) +
  ggtitle("HAR in-sample Forecast for diffusive parts on EURUSD from 2022 May - 2023 Apr") +
  ylab("BPV+J") +
  theme_classic()

EU_dHAR_inpred_plot_bvJ

EU_naive_inpred_plot_bvJ <- ggplot(data=EU_inpred_bvJ, aes(x=date)) +
  geom_line(aes(y=true, color='RVol')) +
  geom_line(aes(y=naive_pred, color='in-sample pred')) +
  scale_color_manual(name=NULL, values=c('RVol' = 'darkgrey', "in-sample pred" = "steelblue")) +
  ggtitle("HAR in-sample Forecast for diffusive parts on EURUSD from 2022 May - 2023 Apr") +
  ylab("BPV+J") +
  theme_classic()

EU_naive_inpred_plot_bvJ
```

## HAR, dHAR and naive out-of-sample prediction for J(ump)
```{r}
EU_HAR_outpred_J <- data.frame(do.call(rbind, lapply(EU_roll_start:EU_roll_end, function(x){comp_har_pred(x-train_length, x, sqrt(EU_daily2$jump))$pred})), row.names = NULL)
EU_dHAR_outpred_J <- data.frame(do.call(rbind, lapply(EU_roll_start:EU_roll_end, function(x){comp_dhar_pred(x-train_length, x, sqrt(EU_daily2$jump))$pred})), row.names = NULL)
EU_naive_outpred_J <- sqrt(EU_daily2$jump[(EU_roll_start+1): (EU_roll_end+1)])
```

## BPV+J out-of-sample forecast
```{r}
# Obtain the one-day out-of-sample forecast of the rolling window
EU_outpred_bvJ <- data.frame(date=EU_daily2$date[(EU_roll_start+2) : (EU_roll_end+2)],
                              true=sqrt(EU_daily2$rvar[(EU_roll_start+2) : (EU_roll_end+2)]),
                              HAR_pred=sqrt(EU_HAR_outpred_bv$fit^2+EU_HAR_outpred_J$fit^2),
                              dHAR_pred=sqrt(EU_HAR_outpred_bv$fit^2+EU_dHAR_outpred_J$fit^2),
                              naive_pred=sqrt(EU_HAR_outpred_bv$fit^2+EU_naive_outpred_J^2))

# Plot the HAR out-of-sample forecast
EU_outpred_plot_bvJ <- ggplot() +
  geom_line(data=data.frame(x=EU_daily2_23$date, y=sqrt(EU_daily2_23$rvar)), 
            aes(x = x, y = y, color = "Rvol")) +
  geom_line(data=data.frame(x=EU_outpred_bvJ$date, y=EU_outpred_bvJ$HAR_pred), 
            aes(x = x, y = y, color = "HAR pred")) +
  geom_line(data=data.frame(x=EU_outpred_bvJ$date, y=EU_outpred_bvJ$dHAR_pred), 
            aes(x = x, y = y, color = "dHAR pred")) +
  geom_line(data=data.frame(x=EU_outpred_bvJ$date, y=EU_outpred_bvJ$naive_pred), 
            aes(x = x, y = y, color = "naive pred")) +
  scale_color_manual(name=NULL, values=c('Rvol' = 'darkgrey', "HAR pred" = "cyan2", 
                                         "dHAR pred"='steelblue', 'naive pred'='blue3')) +
  theme_classic() +
  ggtitle("HAR Out-of-sample Forecast (with 95% CI) on diffusive parts of EURUSD from 2023 Mar - Apr") +
  xlab("date") + ylab("BV")

EU_outpred_plot_bvJ
```
## adj.C + adj.J in-sample forecast
```{r}
EU_daily4 <- EU_daily2[,c('date', 'currency', 'rvar', 'P_rvar', 'N_rvar' ,'rbpv', 'jump','J')]
EU_daily4 <- EU_daily4 %>%
  mutate(adj.j = (rvar - mu1^(-2)*rbpv)*(J < qnorm(0.01, 0, 1))) %>%
  mutate(adj.c = rvar*(J >= qnorm(0.01, 0, 1)) + mu1^(-2)*rbpv*(J < qnorm(0.01, 0, 1)))
```

```{r}
# Estimate the model on full data sample
EU_HAR_in_model_adj.c <- comp_har_pred(23, 256, sqrt(EU_daily4$adj.c))$model
EU_HAR_in_model_adj.c$coefficients
# Compute adjusted R^2 of the fitted adj.c model
base::summary(EU_HAR_in_model_adj.c)$adj.r.squared
EU_HAR_inpred_adj.c <- data.frame(date=EU_daily2$date[24:257], pred=predict(EU_HAR_in_model_adj.c), true=sqrt(EU_daily4$adj.c[24:257]))

# Estimate the model on full data sample
EU_HAR_in_model_adj.j <- comp_har_pred(23, 256, sqrt(EU_daily4$adj.j))$model
EU_HAR_in_model_adj.j$coefficients
base::summary(EU_HAR_in_model_adj.j)$adj.r.squared
EU_HAR_inpred_adj.j <- data.frame(date=EU_daily2$date[24:257], pred=predict(EU_HAR_in_model_adj.j), true=sqrt(EU_daily4$adj.j[24:257]))

EU_dHAR_in_model_adj.j <- comp_dhar_pred(23, 256, sqrt(EU_daily4$adj.j))$model
EU_dHAR_in_model_adj.j$coefficients
base::summary(EU_dHAR_in_model_adj.j)$adj.r.squared
EU_dHAR_inpred_adj.j <- data.frame(date=EU_daily2$date[24:257], pred=predict(EU_dHAR_in_model_adj.j), true=sqrt(EU_daily4$adj.j[24:257]))

# Estimate the model Naive_J
EU_naive_in_adj.j <- sqrt(EU_daily4$adj.j[23:256])

# HAR_adj.c + adj.j
EU_inpred_adj.cj <- data.frame(date=EU_daily2$date[24:257], true=sqrt(EU_daily2$rvar[24:257]),
                               HAR_pred=sqrt((predict(EU_HAR_in_model_adj.c))^2 +
                                               predict(EU_HAR_in_model_adj.j)^2),
                             dHAR_pred=sqrt((predict(EU_HAR_in_model_adj.c))^2 +
                                              predict(EU_dHAR_in_model_adj.j)^2),
                             naive_pred=sqrt((predict(EU_HAR_in_model_adj.c))^2 +
                                               EU_naive_in_adj.j^2))

# Plot the HAR in-sample forecast
EU_HAR_inpred_plot_adj.cj <- ggplot(data=EU_inpred_adj.cj, aes(x=date)) +
  geom_line(aes(y=true, color='RVol')) +
  geom_line(aes(y=HAR_pred, color='in-sample pred')) +
  scale_color_manual(name=NULL, values=c('RVol' = 'darkgrey', "in-sample pred" = "steelblue")) +
  ggtitle("HAR in-sample Forecast for diffusive parts on EURUSD from 2022 May - 2023 Apr") +
  ylab("BPV+J") +
  theme_classic()

EU_HAR_inpred_plot_adj.cj

EU_dHAR_inpred_plot_adj.cj <- ggplot(data=EU_inpred_adj.cj, aes(x=date)) +
  geom_line(aes(y=true, color='RVol')) +
  geom_line(aes(y=dHAR_pred, color='in-sample pred')) +
  scale_color_manual(name=NULL, values=c('RVol' = 'darkgrey', "in-sample pred" = "steelblue")) +
  ggtitle("HAR in-sample Forecast for diffusive parts on EURUSD from 2022 May - 2023 Apr") +
  ylab("BPV+J") +
  theme_classic()

EU_dHAR_inpred_plot_adj.cj

EU_naive_inpred_plot_adj.cj <- ggplot(data=EU_inpred_adj.cj, aes(x=date)) +
  geom_line(aes(y=true, color='RVol')) +
  geom_line(aes(y=naive_pred, color='in-sample pred')) +
  scale_color_manual(name=NULL, values=c('RVol' = 'darkgrey', "in-sample pred" = "steelblue")) +
  ggtitle("HAR in-sample Forecast for diffusive parts on EURUSD from 2022 May - 2023 Apr") +
  ylab("BPV+J") +
  theme_classic()

EU_naive_inpred_plot_adj.cj
```

```{r}
# Obtain the one-day out-of-sample forecast and 0.95 CI of the rolling window
EU_HAR_outpred_adj.c <- data.frame(do.call(rbind, lapply(EU_roll_start:EU_roll_end, function(x){comp_har_pred(x-train_length, x, sqrt(EU_daily4$adj.c))$pred})), row.names = NULL)
EU_HAR_outpred_adj.c$date = EU_daily2$date[(EU_roll_start+2) : (EU_roll_end+2)]
EU_HAR_outpred_adj.c$true = sqrt(EU_daily4$adj.c[(EU_roll_start+2) : (EU_roll_end+2)])

EU_HAR_outpred_adj.j <- data.frame(do.call(rbind, lapply(EU_roll_start:EU_roll_end, function(x){comp_har_pred(x-train_length, x, sqrt(EU_daily4$adj.j))$pred})), row.names = NULL)
EU_dHAR_outpred_adj.j <- data.frame(do.call(rbind, lapply(EU_roll_start:EU_roll_end, function(x){comp_dhar_pred(x-train_length, x, sqrt(EU_daily4$adj.j))$pred})), row.names = NULL)
EU_naive_outpred_adj.j <- sqrt(EU_daily4$adj.j[(EU_roll_start+1): (EU_roll_end+1)])

# Obtain the one-day out-of-sample forecast of the rolling window
EU_outpred_adj.cj <- data.frame(date=EU_daily2$date[(EU_roll_start+2) : (EU_roll_end+2)],
                                true=sqrt(EU_daily2$rvar[(EU_roll_start+2):(EU_roll_end+2)]),
                                HAR_pred=sqrt(EU_HAR_outpred_adj.c$fit^2+EU_HAR_outpred_adj.j$fit^2),
                                dHAR_pred=sqrt(EU_HAR_outpred_adj.c$fit^2+EU_dHAR_outpred_adj.j$fit^2),
                                naive_pred=sqrt(EU_HAR_outpred_adj.c$fit^2+EU_naive_outpred_adj.j^2))

# Plot the HAR out-of-sample forecast
EU_outpred_plot_adj.cj <- ggplot() +
  geom_line(data=data.frame(x=EU_daily2_23$date, y=sqrt(EU_daily2_23$rvar)), 
            aes(x = x, y = y, color = "Rvol")) +
  geom_line(data=data.frame(x=EU_outpred_adj.cj$date, y=EU_outpred_adj.cj$HAR_pred), 
            aes(x = x, y = y, color = "HAR pred")) +
  geom_line(data=data.frame(x=EU_outpred_adj.cj$date, y=EU_outpred_adj.cj$dHAR_pred), 
            aes(x = x, y = y, color = "dHAR pred")) +
  geom_line(data=data.frame(x=EU_outpred_adj.cj$date, y=EU_outpred_adj.cj$naive_pred), 
            aes(x = x, y = y, color = "naive pred")) +
  scale_color_manual(name=NULL, values=c('Rvol' = 'darkgrey', "HAR pred" = "cyan2", 
                                         "dHAR pred"='steelblue', 'naive pred'='blue3')) +
  theme_classic() +
  ggtitle("HAR Out-of-sample Forecast (with 95% CI) on diffusive parts of EURUSD from 2023 Mar - Apr") +
  xlab("date") + ylab("BV")

EU_outpred_plot_adj.cj
```


