---
title: "univariate_probability_forecast"
author: "CID: 01714151"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RV_HAR
### PIT diagram
```{r}
library(scoringRules)
# Gaussian distribution
hist(pghyp(log(EU_daily4$rvar[24:257])- predict(EU_HAR_in_model), gauss(0, 0.4558964)), main="PIT histogram of gauss distribution", xlab="PIT")

# NIG distribution
hist(pghyp(log(EU_daily4$rvar[24:257])- predict(EU_HAR_in_model), RV_HAR_aic.uv$all.models[[4]]), main="PIT histogram of NIG distribution", xlab="PIT")

# VR distribution
hist(pghyp(log(EU_daily4$rvar[24:257])- predict(EU_HAR_in_model), RV_HAR_aic.uv$best.model), main="PIT histogram of VR distribution", xlab="PIT")
acf(pghyp(log(EU_daily4$rvar[24:257])- predict(EU_HAR_in_model), RV_HAR_aic.uv$best.model), main="ACF of PIT of VR")
```
### LS score
```{r}
comp_LS_score <- function(y, object){
  fy = dghyp(y, object)
  return(-log(fy))
}

# Gaussian distribution
mean(comp_LS_score(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), gauss(0, 0.4558964)))
# NIG distribution
mean(comp_LS_score(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), RV_HAR_aic.uv$all.models[[4]]))
# VR distribution
mean(comp_LS_score(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), RV_HAR_aic.uv$best.model))
```

### DS score
```{r}
library(VarianceGamma)

comp_dss_score <- function(obs, mean, sigma){
  dff <- (obs-mean)^2/sigma^2 + 2*log(sigma)
  return(dff)
}

mean(unlist(lapply(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), function(obs){comp_dss_score(obs, 0, 0.4558964)})))

mean(unlist(lapply(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), function(obs){comp_dss_score(obs, vgMean(vgC = -0.3406849, sigma = 0.3981939, theta = 0.3407129, nu = 1/2.0180085), sqrt(vgVar(vgC = -0.3406849, sigma = 0.3981939, theta = 0.3407129, nu = 1/2.0180085)))})))

#var(rghyp(100000, VG(lambda=2.0180085, mu=-0.3406849, sigma=0.3981939, gamma=0.3407129)))
```

### crps score
```{r}
# gaussian distribution
mean(crps_norm(log(EU_daily4$rvar[24:257]), predict(EU_HAR_in_model), 0.4558964))
# t distribution
mean(crps_t(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), 8.31084628, -2.844532e-02, 0.45770874))
```

### in-sample probablistic forecast plot
```{r}
# Plot the HAR in-sample forecast
EU_HAR_inprob_plot <- ggplot(data=EU_HAR_inpred, aes(x=date)) +
  geom_line(aes(y=true, color='log(RV)')) +
  #geom_line(aes(y=pred, color='HAR_RV pred')) +
  geom_ribbon(data=data.frame(x=EU_HAR_inpred$date, 
                              lwr = qnorm(0.05, predict(EU_HAR_in_model), 0.4558964),
                              upr = qnorm(0.95, predict(EU_HAR_in_model), 0.4558964)),
              aes(x = x, ymin = lwr, ymax=upr), fill = "steelblue", alpha=0.3) +
  geom_ribbon(data=data.frame(x=EU_HAR_inpred$date, 
                              lwr = qnorm(0.15, predict(EU_HAR_in_model), 0.4558964),
                              upr = qnorm(0.85, predict(EU_HAR_in_model), 0.4558964)),
              aes(x = x, ymin = lwr, ymax=upr), fill = "steelblue", alpha=0.3) +
  geom_ribbon(data=data.frame(x=EU_HAR_inpred$date, 
                              lwr = qnorm(0.25, predict(EU_HAR_in_model), 0.4558964),
                              upr = qnorm(0.75, predict(EU_HAR_in_model), 0.4558964)),
              aes(x = x, ymin = lwr, ymax=upr), fill = "steelblue", alpha=0.3) +
  geom_ribbon(data=data.frame(x=EU_HAR_inpred$date, 
                              lwr = qnorm(0.35, predict(EU_HAR_in_model), 0.4558964),
                              upr = qnorm(0.65, predict(EU_HAR_in_model), 0.4558964)),
              aes(x = x, ymin = lwr, ymax=upr), fill = "steelblue", alpha=0.3) +
  geom_ribbon(data=data.frame(x=EU_HAR_inpred$date, 
                              lwr = qnorm(0.45, predict(EU_HAR_in_model), 0.4558964),
                              upr = qnorm(0.55, predict(EU_HAR_in_model), 0.4558964)),
              aes(x = x, ymin = lwr, ymax=upr), fill = "steelblue", alpha=0.3) +
  scale_color_manual(name=NULL, values=c('log(RV)' = 'black')) +
  #ggtitle("HAR in-sample Forecast on EURUSD from 2022 May - 2023 Apr") +
  ylab("RVol") +
  xlab("Date") +
  theme_classic() +
  theme(axis.title = element_text(size= 12.5),
        axis.text = element_text(size= 11.5),
        legend.title = element_text(size= 11),
        legend.text = element_text(size= 11),
        legend.position = c(0.9, 0.85))

EU_HAR_inprob_plot
```
## HAR_BV+J
### PIT diagram
```{r}
library(scoringRules)
# Gaussian distribution
hist(pghyp(log(EU_daily4$rvar[24:257])- EU_inpred_bvJ$HAR_pred, gauss(0, 0.4099977)), main="PIT histogram of gauss distribution", xlab="PIT")

# NIG distribution
hist(pghyp(log(EU_daily4$rvar[24:257])- EU_inpred_bvJ$HAR_pred, HAR_BVJ_aic.uv$all.models[[3]]), main="PIT histogram of NIG distribution", xlab="PIT")

# VR distribution
hist(pghyp(log(EU_daily4$rvar[24:257])- EU_inpred_bvJ$HAR_pred, HAR_BVJ_aic.uv$best.model), main="PIT histogram of VR distribution", xlab="PIT")
acf(pghyp(log(EU_daily4$rvar[24:257])- EU_inpred_bvJ$HAR_pred, HAR_BVJ_aic.uv$best.model), main="ACF of PIT of VR")
```
### LS score
```{r}
comp_LS_score <- function(y, object){
  fy = dghyp(y, object)
  return(-log(fy))
}

# Gaussian distribution
mean(comp_LS_score(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), gauss(0, 0.4558964)))
# NIG distribution
mean(comp_LS_score(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), RV_HAR_aic.uv$all.models[[4]]))
# VR distribution
mean(comp_LS_score(log(EU_daily4$rvar[24:257])-predict(EU_HAR_in_model), RV_HAR_aic.uv$best.model))
```

